name: Synchronize with template repository
description: Synchronize repository with template repository

inputs:
  configFile:
    required: true
    default: '.github/sync-with-template.yml'
    description: Path to config file
  filesToDeleteFile:
    required: false
    default: '.github/sync-with-template-delete.list'
    description: Path to a file with a list of files to delete
  localTransformationsFile:
    required: true
    default: '.github/sync-with-template-local-transformations.yml'
    description: Path to local transformations file
  githubToken:
    required: true
    description: GitHub access token with at least 'public_repo' and 'workflow' scopes (use 'repo' scope instead of 'public_repo' for private repositories)
  templateRepository:
    required: false
    description: Template repository full name (owner/repo). GitHub template repository information is used by default.
  syncBranchName:
    required: true
    default: 'template-sync'
    description: Git branch name that is used for synchronization with template repository
  conventionalCommits:
    required: true
    default: 'false'
    description: Set to 'true' to enable using Conventional Commits
  commitMessage:
    required: true
    default: 'Template repository changes: <template-repository>'
    description: Commit message
  dryRun:
    required: true
    default: 'false'
    description: Set to 'true' to disable Git push

runs:
  using: node20
  main: dist/index.js
  #post: dist/index.js
