name: Synchronize with template repository
description: Synchronize repository with template repository

inputs:
  githubToken:
    required: true
    description: GitHub access token with at least 'public_repo' and 'workflow' scopes (use 'repo' scope instead of 'public_repo' for private repositories)
  templateRepository:
    required: false
    description: Template repository full name (owner/repo). GitHub template repository information is used by default.
  syncBranchName:
    required: true
    default: 'template-sync'
    description: Git branch name that is used for synchronization with template repository
  conventionalCommits:
    required: true
    default: 'false'
    description: Set to 'true' to enable using Conventional Commits
  lfs:
    required: true
    default: 'false'
    description: Set to 'true' to enable LFS

runs:
  using: node12
  main: 'dist/index.js'
