 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Glob = string;

/**
 * Config for sync-with-template GitHub action
 */
export interface Config {
  /**
   * Glob patterns for included files
   *
   * @minItems 1
   */
  includes: [Glob, ...Glob[]];
  /**
   * Glob patterns for excluded files
   */
  excludes?: Glob[];
}
