/* tslint:disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type Glob = string;
/**
 * Local transformations for sync-with-template GitHub action
 */
export type LocalTransformations = FilesTransformation[];

export interface FilesTransformation {
  /**
   * Transformation name
   */
  name: string;
  /**
   * Glob patterns for included files
   *
   * @minItems 1
   */
  includes: [Glob, ...Glob[]];
  /**
   * Glob patterns for excluded files
   */
  excludes?: Glob[];
  /**
   * File format
   */
  format: "text";
  /**
   * File to replace the matched file with
   */
  replaceWith?: string;
  /**
   * JavaScript code transforming files
   */
  script?: string;
}
