 
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type RepositoryFullName = string;
export type Glob = string;

/**
 * Local transformations for sync-with-template GitHub action
 */
export interface LocalTransformations {
  /**
   * @minItems 1
   */
  repositories: [RepositoryFullName, ...RepositoryFullName[]];
  transformations?: FilesTransformation[];
}
export interface FilesTransformation {
  /**
   * Transformation name
   */
  name: string;
  /**
   * Glob patterns for included files
   *
   * @minItems 1
   */
  includes: [Glob, ...Glob[]];
  /**
   * Glob patterns for excluded files
   */
  excludes?: Glob[];
  /**
   * File format
   */
  format: "text" | "json" | "json5" | "yaml";
  /**
   * File indent
   */
  indent?: number;
  /**
   * Set to true to exclude files from the synchronization
   */
  ignore?: boolean;
  /**
   * File to replace the matched file with
   */
  replaceWithFile?: string;
  /**
   * File to replace the matched file with
   */
  replaceWithText?: string;
  /**
   * JavaScript code transforming files
   */
  script?: string;
  /**
   * Set to true to delete files
   */
  delete?: boolean;
}
