name: Install dependencies
description: Get the package manager from `package.json` and install dependencies, using a cache

inputs:
  nodeVersion:
    description: Node.js version (used in the dependencies cache key)
    required: true

outputs:
  result:
    description: Package manager (e.g. `yarn`)
    value: ${{steps.package-manager.outputs.result}}
  name:
    description: Capitalized package manager name (e.g. `Yarn`)
    value: ${{steps.package-manager.outputs.name}}

runs:
  using: composite
  steps:
  - name: Get package manager
    id: package-manager
    shell: bash
    run: |
      PACKAGE_MANAGER=$( yq -r '.packageManager' ./package.json )
      PACKAGE_MANAGER=${PACKAGE_MANAGER%%@*}
      if ! [[ "$PACKAGE_MANAGER" =~ ^[a-z]+$ ]]; then
        echo "::error::package.json: unsupported .packageManager format: '$PACKAGE_MANAGER'"
        exit 1
      fi
      echo "PACKAGE_MANAGER=$PACKAGE_MANAGER" | tee -a "$GITHUB_ENV"
      echo "result=$PACKAGE_MANAGER" | tee -a "$GITHUB_OUTPUT"
      PACKAGE_MANAGER_NAME=${PACKAGE_MANAGER^}
      echo "name=$PACKAGE_MANAGER_NAME" | tee -a "$GITHUB_OUTPUT"

  - name: Create cache params
    id: cache-params
    shell: bash
    env:
      CACHE_KEY: ${{runner.os}}-dependencies-${{inputs.nodeVersion}}-${{hashFiles('package.json', 'pnpm-*.yml', '.yarnrc.yml', 'yarn.lock' , '.pnp.*', '.yarn/patches/**', '.yarn/plugins/**', '.yarn/releases/**', '.yarn/versions/**')}}
    run: |
      echo "key=$CACHE_KEY" | tee -a "$GITHUB_OUTPUT"
      echo "paths<<EOF" | tee -a "$GITHUB_OUTPUT"
      echo "node_modules" | tee -a "$GITHUB_OUTPUT"
      echo ".yarn/cache" | tee -a "$GITHUB_OUTPUT"
      echo "EOF" | tee -a "$GITHUB_OUTPUT"

  - name: Restore dependencies cache
    id: restore-dependencies-cache
    uses: actions/cache/restore@v6
    with:
      key: ${{steps.cache-params.outputs.key}}
      path: ${{steps.cache-params.outputs.paths}}

  - name: Install dependencies
    shell: bash
    run: |
      if [ "$PACKAGE_MANAGER" == "pnpm" ]; then
        pnpm install --no-frozen-lockfile
      elif [ "$PACKAGE_MANAGER" == "yarn" ]; then
        yarn install --no-immutable
      else
        echo "::error::Unsupported package manager: $PACKAGE_MANAGER"
        exit 1
      fi

  - name: Save dependencies cache
    if: ${{steps.restore-dependencies-cache.outputs.cache-hit != 'true'}}
    uses: actions/cache/save@v6
    with:
      key: ${{steps.cache-params.outputs.key}}
      path: ${{steps.cache-params.outputs.paths}}
