name: build

on:
  push:
    branches:
    - main
  pull_request: { }
  schedule:
  - cron: '53 17 * * 4' # sync-with-template: adjust
  workflow_dispatch: { }

permissions:
  id-token: write

defaults:
  run:
    shell: bash

jobs:
  build:
    if: ${{
      (github.event_name == 'push' && startsWith(github.ref, 'refs/tags/'))
      || (github.event_name == 'push' && !startsWith(github.event.head_commit.message, '[push-back]'))
      || github.event_name != 'push'
      }}
    concurrency:
      group: build-${{github.ref}}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
    - name: Get GitHub Token
      id: get-token
      uses: remal/github-repository-token-issuer@v1
      with:
        scopes: |
          contents: write
          workflows: write

    - name: Checkout repository
      uses: actions/checkout@v7
      with:
        token: ${{steps.get-token.outputs.token}}
        submodules: recursive
        lfs: true
        fetch-depth: 1


    - name: Read action's Node.js version
      id: read-node-version
      uses: ./.github/actions/read-action-nodejs-version

    - name: Setup Node.js ${{steps.read-node-version.outputs.result}}
      uses: actions/setup-node@v6
      with:
        node-version: '${{steps.read-node-version.outputs.result}}'

    - name: Update Node.js version in project files
      env:
        NODE_VERSION: ${{steps.read-node-version.outputs.result}}
      run: |
        node update-node-version-in-files "$NODE_VERSION"


    - name: Install dependencies
      uses: ./.github/actions/install-dependencies
      with:
        nodeVersion: '${{steps.read-node-version.outputs.result}}'


    # $$$sync-with-template-modifiable: code generation $$$
    # $$$sync-with-template-modifiable-end$$$


    - name: Build
      run: |
        "$PACKAGE_MANAGER" run build

    - name: Upload dist to artifacts
      if: ${{always()}}
      uses: actions/upload-artifact@v7
      with:
        name: dist
        path: dist/
        if-no-files-found: error
        overwrite: true
        retention-days: 30


    # $$$sync-with-template-modifiable: validation $$$

    - name: Run current action
      uses: ./
      with:
        dryRun: 'true'
        githubToken: ${{github.token}}

    # $$$sync-with-template-modifiable-end$$$


    - name: Push back
      if: ${{startsWith(github.ref, 'refs/heads/')}}
      uses: remal-github-actions/push-back@v2
      with:
        message: '[push-back] Push-back updated files during build'


    - name: Read version
      id: readVersion
      if: ${{github.ref == 'refs/heads/main'}}
      uses: remal-github-actions/read-nodejs-package-version@v1

    - name: Remove files listed in .releaseignore
      if: ${{github.ref == 'refs/heads/main'}}
      id: releaseignore
      uses: actions/github-script@v9
      with:
        script: |
          const fs = require('fs')
          const path = require('path')

          const cwdPath = path.resolve(process.cwd())

          const releaseIgnorePath = '.releaseignore'
          const releaseIgnoreFullPath = path.resolve(cwdPath, releaseIgnorePath)
          if (!fs.existsSync(releaseIgnoreFullPath)) {
            core.info(`${releaseIgnorePath} file does not exist, skipping removal of files.`)
            core.setOutput('skipped', 'true')
            return
          }

          let patternsToIgnore = fs.readFileSync(releaseIgnoreFullPath, 'utf-8')
            .split('\n')
            .map(line => line.replace(/#.*/, '').trim())
            .filter(line => line.length)
            .join('\n')
          if (!patternsToIgnore.length) {
            core.info(`${releaseIgnorePath} file does not have patterns, skipping removal of files.`)
            core.setOutput('skipped', 'true')
            return
          }

          const gitDirPath = path.resolve(cwdPath, '.git')

          const globber = await glob.create(patternsToIgnore)
          const files = await globber.glob()
          files
            .map(file => path.resolve(cwdPath, file))
            .filter(file => file != cwdPath)
            .filter(file => file != gitDirPath && !file.startsWith(gitDirPath + path.sep))
            .forEach(file => {
              core.debug(`Removing: ${file}`)
              fs.rmSync(file, { recursive: true, force: true })
            })

    - name: Prepare release commit
      if: ${{github.ref == 'refs/heads/main' && !steps.releaseignore.outputs.skipped}}
      env:
        MAJOR_VERSION: ${{steps.readVersion.outputs.majorVersion}}
      run: |
        RELEASE_BRANCH="release/v$MAJOR_VERSION"
        git switch --force-create "$RELEASE_BRANCH"
        git add --all
        git commit -m "[skip-ci] Release v$MAJOR_VERSION" || true
        git push --force origin "$RELEASE_BRANCH"

    - name: Create tag
      if: ${{github.ref == 'refs/heads/main'}}
      uses: remal-github-actions/create-tag@v2
      with:
        tagName: 'v${{steps.readVersion.outputs.majorVersion}}'
